# -*- coding: utf-8 -*-
"""Efficient evolution with protein language models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18QLOmi5yNb1i9wztAzv981Wgk2E4IP4q

# Efficient evolution with protein language models

**Warning**: Running this notebook **requires a high-memory Colab instance** (only available via Colab Pro) and will be **very slow** (~45 minutes), as it requires downloading all of the models beforehand. If you want to make predictions for many wildtype sequences, we recommend installing (and reusing) the models from a local compute instance, as described here: https://github.com/brianhie/efficient-evolution#running-the-model.
"""

#@title Input the protein sequence, then hit the `Run` button on the left.

!pip install fair-esm==0.4.0 biopython > pip_install.log 2>&1

wildtype_sequence = 'QVQLQQSGPGLVKPSQTLSLTCAISGDSVSSYNAVWNWIRQSPSRGLEWLGRTYYRSGWYNDYAESVKSRITINPDTSKNQFSLQLNSVTPEDTAVYYCARSGHITVFGVNVDAFDMWGQGTMVTVSS' #@param {type:"string"}

!git clone https://github.com/brianhie/efficient-evolution.git > git_clone.log 2>&1
!python efficient-evolution/bin/recommend.py $wildtype_sequence