# -*- coding: utf-8 -*-
"""03_Devices_00_Noise_Base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lUSsAFjneqR_QhFnL6dZxkBzm2uI7NvU
"""

# Install relevant packages
!pip install qiskit
!pip install qiskit_aer
!pip install --verbose dynacir==0.1.4

from dynacir.dynacir_noisemodel import get_secret_noise_model
from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator

qc = QuantumCircuit(5)
qc.h(0)
qc.measure_all()

secret_noise_model = get_secret_noise_model()

simulator = AerSimulator()

job = simulator.run(qc, noise_model = secret_noise_model)
job.result().get_counts()